services:
  scraper:
    container_name: isos-scraper
    build:
      context: .              
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env    
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - isos-network

networks:
  isos-network:
    external: true