"""law_texte and commission text on stages

Revision ID: 058a2d0e6411
Revises: 87d289da2255
Create Date: 2026-09-21 09:22:02.490251

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "058a2d0e6411"
down_revision: str | Sequence[str] | None = "87d289da2255"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "law_texte",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.String(length=100), nullable=False),
        sa.Column("dossier_uid", sa.String(length=100), nullable=False),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=True),
        sa.Column("sub_kind", sa.String(length=50), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("short_title", sa.Text(), nullable=True),
        sa.Column("deposited_at", sa.Date(), nullable=True),
        sa.Column("author_uids", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("organe_uids", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_uid"],
            ["raw.law.dossier_uid"],
            name=op.f("fk_law_texte_dossier_uid"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_law_texte")),
        sa.UniqueConstraint("uid", name=op.f("uq_law_texte_uid")),
        schema="raw",
    )
    op.create_index(
        "ix_raw_law_texte_dossier", "law_texte", ["dossier_uid"], unique=False, schema="raw"
    )
    op.create_index(
        "ix_raw_law_texte_number",
        "law_texte",
        ["legislature", "number"],
        unique=False,
        schema="raw",
    )
    op.add_column(
        "law_stage",
        sa.Column("commission_texte_uid", sa.String(length=100), nullable=True),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("law_stage", "commission_texte_uid", schema="raw")
    op.drop_index("ix_raw_law_texte_number", table_name="law_texte", schema="raw")
    op.drop_index("ix_raw_law_texte_dossier", table_name="law_texte", schema="raw")
    op.drop_table("law_texte", schema="raw")
    # ### end Alembic commands ###
