"""law_stage adopted_texte_uid

Revision ID: 1bf1fe25d12c
Revises: da7493524169
Create Date: 2026-09-21 12:53:45.157001

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bf1fe25d12c"
down_revision: str | Sequence[str] | None = "da7493524169"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "law_stage",
        sa.Column("adopted_texte_uid", sa.String(length=100), nullable=True),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("law_stage", "adopted_texte_uid", schema="raw")
    # ### end Alembic commands ###
