"""law and law_stage from real dossiers

Revision ID: 4fb475a95ba8
Revises: 2ac502cf62a5
Create Date: 2026-09-21 04:13:24.531189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4fb475a95ba8"
down_revision: str | Sequence[str] | None = "2ac502cf62a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("law", sa.Column("senate_url", sa.Text(), nullable=True), schema="raw")
    op.add_column(
        "law", sa.Column("procedure_code", sa.String(length=10), nullable=False), schema="raw"
    )
    op.add_column("law", sa.Column("procedure_label", sa.Text(), nullable=True), schema="raw")
    op.add_column(
        "law",
        sa.Column(
            "initiator_uids", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        schema="raw",
    )
    op.add_column(
        "law",
        sa.Column("withdrawn", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        schema="raw",
    )
    op.drop_index(op.f("ix_raw_law_texte_uid"), table_name="law", schema="raw")
    op.drop_column("law", "texte_uid", schema="raw")
    op.drop_column("law", "closure_status", schema="raw")
    op.drop_column("law", "law_type", schema="raw")
    op.drop_column("law", "initiateur_uid", schema="raw")
    op.add_column(
        "law_stage", sa.Column("stage_uid", sa.String(length=100), nullable=False), schema="raw"
    )
    op.add_column(
        "law_stage", sa.Column("organe_ref", sa.String(length=100), nullable=True), schema="raw"
    )
    op.add_column("law_stage", sa.Column("started_at", sa.Date(), nullable=True), schema="raw")
    op.add_column("law_stage", sa.Column("examined_at", sa.Date(), nullable=True), schema="raw")
    op.add_column("law_stage", sa.Column("concluded_at", sa.Date(), nullable=True), schema="raw")
    op.add_column("law_stage", sa.Column("decision", sa.Text(), nullable=True), schema="raw")
    op.add_column(
        "law_stage", sa.Column("decision_code", sa.String(length=20), nullable=True), schema="raw"
    )
    op.add_column(
        "law_stage", sa.Column("texte_uid", sa.String(length=100), nullable=True), schema="raw"
    )
    op.add_column(
        "law_stage",
        sa.Column("sitting_refs", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        schema="raw",
    )
    op.drop_constraint(op.f("uq_raw_law_stage"), "law_stage", schema="raw", type_="unique")
    op.create_index(
        "ix_raw_law_stage_dossier", "law_stage", ["dossier_uid"], unique=False, schema="raw"
    )
    op.create_unique_constraint(
        op.f("uq_law_stage_stage_uid"), "law_stage", ["stage_uid"], schema="raw"
    )
    op.drop_column("law_stage", "updated_stage_date", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "law_stage",
        sa.Column("updated_stage_date", sa.DATE(), autoincrement=False, nullable=True),
        schema="raw",
    )
    op.drop_constraint(op.f("uq_law_stage_stage_uid"), "law_stage", schema="raw", type_="unique")
    op.drop_index("ix_raw_law_stage_dossier", table_name="law_stage", schema="raw")
    op.create_unique_constraint(
        op.f("uq_raw_law_stage"),
        "law_stage",
        ["dossier_uid", "code", "position"],
        schema="raw",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("law_stage", "sitting_refs", schema="raw")
    op.drop_column("law_stage", "texte_uid", schema="raw")
    op.drop_column("law_stage", "decision_code", schema="raw")
    op.drop_column("law_stage", "decision", schema="raw")
    op.drop_column("law_stage", "concluded_at", schema="raw")
    op.drop_column("law_stage", "examined_at", schema="raw")
    op.drop_column("law_stage", "started_at", schema="raw")
    op.drop_column("law_stage", "organe_ref", schema="raw")
    op.drop_column("law_stage", "stage_uid", schema="raw")
    op.add_column(
        "law",
        sa.Column("initiateur_uid", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        schema="raw",
    )
    op.add_column(
        "law",
        sa.Column("law_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        schema="raw",
    )
    op.add_column(
        "law",
        sa.Column("closure_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        schema="raw",
    )
    op.add_column(
        "law",
        sa.Column("texte_uid", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        schema="raw",
    )
    op.create_index(op.f("ix_raw_law_texte_uid"), "law", ["texte_uid"], unique=False, schema="raw")
    op.drop_column("law", "withdrawn", schema="raw")
    op.drop_column("law", "initiator_uids", schema="raw")
    op.drop_column("law", "procedure_label", schema="raw")
    op.drop_column("law", "procedure_code", schema="raw")
    op.drop_column("law", "senate_url", schema="raw")
    # ### end Alembic commands ###
