"""law_article mention is text

Revision ID: 558913948488
Revises: 1bf1fe25d12c
Create Date: 2026-09-21 13:00:16.248539

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "558913948488"
down_revision: str | Sequence[str] | None = "1bf1fe25d12c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "law_article",
        "mention",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Text(),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "law_article",
        "mention",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###
