"""government_role and deputy.is_deputy (AMO30)

Revision ID: 66b328f6a924
Revises: 279a47116401
Create Date: 2026-09-21 10:33:20.354455

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66b328f6a924"
down_revision: str | Sequence[str] | None = "279a47116401"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "government_role",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.String(length=100), nullable=False),
        sa.Column("deputy_uid", sa.String(length=100), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("ministry_uid", sa.String(length=100), nullable=True),
        sa.Column("ministry", sa.Text(), nullable=True),
        sa.Column("start", sa.Date(), nullable=True),
        sa.Column("end", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deputy_uid"],
            ["raw.deputy.uid"],
            name=op.f("fk_government_role_deputy_uid"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_government_role")),
        sa.UniqueConstraint("uid", name=op.f("uq_government_role_uid")),
        schema="raw",
    )
    op.create_index(
        "ix_raw_government_role_deputy",
        "government_role",
        ["deputy_uid"],
        unique=False,
        schema="raw",
    )
    op.add_column(
        "deputy",
        sa.Column("is_deputy", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deputy", "is_deputy", schema="raw")
    op.drop_index("ix_raw_government_role_deputy", table_name="government_role", schema="raw")
    op.drop_table("government_role", schema="raw")
    # ### end Alembic commands ###
