"""drop law_article: article text is not in open data

Revision ID: 7cfd18a2df15
Revises: 4fb475a95ba8
Create Date: 2026-09-21 04:40:55.301456

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7cfd18a2df15"
down_revision: str | Sequence[str] | None = "4fb475a95ba8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_raw_law_article_current"),
        table_name="law_article",
        schema="raw",
        postgresql_where="is_current",
    )
    op.drop_table("law_article", schema="raw")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "law_article",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("texte_uid", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("article_ref", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("article_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("legislature", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content_checksum", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "version_number",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_current",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "superseded_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("amendment_uid", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("s3_key", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "scraped_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_law_article")),
        schema="raw",
    )
    op.create_index(
        op.f("uq_raw_law_article_current"),
        "law_article",
        ["texte_uid", "article_ref"],
        unique=True,
        schema="raw",
        postgresql_where="is_current",
    )
    # ### end Alembic commands ###
