"""ballot, ballot_group, ballot_vote

Revision ID: 7e8ab396d72c
Revises: 66b328f6a924
Create Date: 2026-09-21 10:48:30.550445

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e8ab396d72c"
down_revision: str | Sequence[str] | None = "66b328f6a924"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ballot",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.String(length=100), nullable=False),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("sitting_uid", sa.String(length=100), nullable=False),
        sa.Column("session_ref", sa.String(length=50), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("kind_label", sa.Text(), nullable=True),
        sa.Column("majority_rule", sa.Text(), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.Text(), nullable=True),
        sa.Column("dossier_uid", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=50), nullable=True),
        sa.Column("voters", sa.Integer(), nullable=True),
        sa.Column("expressed", sa.Integer(), nullable=True),
        sa.Column("required", sa.Integer(), nullable=True),
        sa.Column("for_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("against_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("abstention_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("non_voting_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("non_voting_voluntary_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("s3_key", sa.Text(), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["raw.ingestion_run.id"],
            name=op.f("fk_ballot_ingestion_run_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ballot")),
        sa.UniqueConstraint("uid", name=op.f("uq_ballot_uid")),
        schema="raw",
    )
    op.create_index("ix_raw_ballot_dossier", "ballot", ["dossier_uid"], unique=False, schema="raw")
    op.create_index("ix_raw_ballot_sitting", "ballot", ["sitting_uid"], unique=False, schema="raw")
    op.create_table(
        "ballot_group",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ballot_uid", sa.String(length=100), nullable=False),
        sa.Column("group_uid", sa.String(length=100), nullable=False),
        sa.Column("members", sa.Integer(), nullable=True),
        sa.Column("majority_position", sa.String(length=30), nullable=True),
        sa.Column("for_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("against_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("abstention_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("non_voting_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["ballot_uid"],
            ["raw.ballot.uid"],
            name=op.f("fk_ballot_group_ballot_uid"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ballot_group")),
        sa.UniqueConstraint("ballot_uid", "group_uid", name="uq_raw_ballot_group"),
        schema="raw",
    )
    op.create_table(
        "ballot_vote",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ballot_uid", sa.String(length=100), nullable=False),
        sa.Column("deputy_uid", sa.String(length=100), nullable=False),
        sa.Column("mandate_uid", sa.String(length=100), nullable=True),
        sa.Column("group_uid", sa.String(length=100), nullable=True),
        sa.Column("position", sa.String(length=30), nullable=False),
        sa.Column("by_delegation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("corrected_position", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["ballot_uid"],
            ["raw.ballot.uid"],
            name=op.f("fk_ballot_vote_ballot_uid"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ballot_vote")),
        sa.UniqueConstraint("ballot_uid", "deputy_uid", name="uq_raw_ballot_vote"),
        schema="raw",
    )
    op.create_index(
        "ix_raw_ballot_vote_deputy", "ballot_vote", ["deputy_uid"], unique=False, schema="raw"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_ballot_vote_deputy", table_name="ballot_vote", schema="raw")
    op.drop_table("ballot_vote", schema="raw")
    op.drop_table("ballot_group", schema="raw")
    op.drop_index("ix_raw_ballot_sitting", table_name="ballot", schema="raw")
    op.drop_index("ix_raw_ballot_dossier", table_name="ballot", schema="raw")
    op.drop_table("ballot", schema="raw")
    # ### end Alembic commands ###
