"""amendment number is a string

Revision ID: 87d289da2255
Revises: be1b04368250
Create Date: 2026-09-21 05:21:17.919889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87d289da2255"
down_revision: str | Sequence[str] | None = "be1b04368250"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "amendment",
        "number",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=20),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "amendment",
        "number",
        existing_type=sa.String(length=20),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###
