"""amendment

Revision ID: 93f07fa1b126
Revises: 7cfd18a2df15
Create Date: 2026-09-21 05:02:37.990564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "93f07fa1b126"
down_revision: str | Sequence[str] | None = "7cfd18a2df15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amendment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uid", sa.String(length=100), nullable=False),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column("dossier_uid", sa.String(length=100), nullable=True),
        sa.Column("texte_uid", sa.String(length=100), nullable=False),
        sa.Column("examen_ref", sa.String(length=100), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("rectification", sa.Integer(), server_default="0", nullable=False),
        sa.Column("examined_by", sa.String(length=50), nullable=True),
        sa.Column("parent_uid", sa.String(length=100), nullable=True),
        sa.Column("author_type", sa.String(length=50), nullable=False),
        sa.Column("deputy_uid", sa.String(length=100), nullable=True),
        sa.Column("group_uid", sa.String(length=100), nullable=True),
        sa.Column(
            "cosigner_uids", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("signatories", sa.Text(), nullable=True),
        sa.Column("division_title", sa.Text(), nullable=True),
        sa.Column("division_type", sa.String(length=50), nullable=True),
        sa.Column("division_position", sa.String(length=20), nullable=True),
        sa.Column("alinea", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("deposited_at", sa.Date(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("sub_state", sa.String(length=100), nullable=True),
        sa.Column("sort", sa.String(length=50), nullable=True),
        sa.Column("sorted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("s3_key", sa.Text(), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["raw.ingestion_run.id"],
            name=op.f("fk_amendment_ingestion_run_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amendment")),
        sa.UniqueConstraint("uid", name=op.f("uq_amendment_uid")),
        schema="raw",
    )
    op.create_index(
        "ix_raw_amendment_deputy", "amendment", ["deputy_uid"], unique=False, schema="raw"
    )
    op.create_index(
        "ix_raw_amendment_dossier", "amendment", ["dossier_uid"], unique=False, schema="raw"
    )
    op.create_index(
        "ix_raw_amendment_texte", "amendment", ["texte_uid"], unique=False, schema="raw"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_amendment_texte", table_name="amendment", schema="raw")
    op.drop_index("ix_raw_amendment_dossier", table_name="amendment", schema="raw")
    op.drop_index("ix_raw_amendment_deputy", table_name="amendment", schema="raw")
    op.drop_table("amendment", schema="raw")
    # ### end Alembic commands ###
