"""amendment alinea is a designation

Revision ID: be1b04368250
Revises: 93f07fa1b126
Create Date: 2026-09-21 05:14:03.643625

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be1b04368250"
down_revision: str | Sequence[str] | None = "93f07fa1b126"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "amendment",
        "alinea",
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "amendment",
        "alinea",
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="raw",
    )
    # ### end Alembic commands ###
