"""law_text and law_article from the website

Revision ID: da7493524169
Revises: 4c7cbf1883e6
Create Date: 2026-09-21 12:48:52.237730

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da7493524169"
down_revision: str | Sequence[str] | None = "4c7cbf1883e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "law_text",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("texte_uid", sa.String(length=100), nullable=False),
        sa.Column("dossier_uid", sa.String(length=100), nullable=True),
        sa.Column("legislature", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=True),
        sa.Column("available", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("article_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("s3_key", sa.Text(), nullable=True),
        sa.Column("ingestion_run_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["raw.ingestion_run.id"],
            name=op.f("fk_law_text_ingestion_run_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_law_text")),
        sa.UniqueConstraint("texte_uid", name=op.f("uq_law_text_texte_uid")),
        schema="raw",
    )
    op.create_index(
        "ix_raw_law_text_dossier", "law_text", ["dossier_uid"], unique=False, schema="raw"
    )
    op.create_table(
        "law_article",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("texte_uid", sa.String(length=100), nullable=False),
        sa.Column("article_ref", sa.Text(), nullable=False),
        sa.Column("is_new", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("mention", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["texte_uid"],
            ["raw.law_text.texte_uid"],
            name=op.f("fk_law_article_texte_uid"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_law_article")),
        sa.UniqueConstraint("texte_uid", "position", name="uq_raw_law_article"),
        schema="raw",
    )
    op.create_index(
        "ix_raw_law_article_ref",
        "law_article",
        ["texte_uid", "article_ref"],
        unique=False,
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_raw_law_article_ref", table_name="law_article", schema="raw")
    op.drop_table("law_article", schema="raw")
    op.drop_index("ix_raw_law_text_dossier", table_name="law_text", schema="raw")
    op.drop_table("law_text", schema="raw")
    # ### end Alembic commands ###
